name: Claude PR Review

on:
  issue_comment:
    types: [created]

# Ensure only one review runs per PR at a time
concurrency:
  group: claude-review-${{ github.event.issue.number }}
  cancel-in-progress: false

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  claude-review:
    # Only run on PR comments that mention "@claude" anywhere
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '@claude')

    # Call the centralized reusable workflow from the .github organization repository
    uses: quantivly/.github/.github/workflows/claude-review.yml@master
    # Pass all organization secrets to the reusable workflow
    # Required secrets: ANTHROPIC_API_KEY
    # Optional secrets: LINEAR_API_KEY, CLAUDE_APP_PRIVATE_KEY
    # Required variables: CLAUDE_APP_ID (for Claude[bot] identity)
    secrets: inherit
